:r "Database\Entity_Types\Building.sql"
:r "Database\Entity_Types\Patient.sql"
:r "Database\Entity_Types\Staff.sql"
:r "Database\Entity_Types\Symptom.sql"
:r "Database\Entity_Types\Inventory.sql"
:r "Database\Entity_Types\Room.sql"
:r "Database\Entity_Types\Home.sql"
:r "Database\Entity_Types\VisitHistory.sql"
:r "Database\Relationship_types\StaysIn.sql"
:r "Database\Relationship_types\Present.sql"
:r "Database\Relationship_types\ChecksIn.sql"
:r "Database\Relationship_types\ChecksOut.sql"
:r "Database\Relationship_types\Diagnoses.sql"
:r "Database\Relationship_types\Modifies.sql"
--:r "Database\StoredProcedures\StoredProcedures.sql"  --Uncomment this line when the Stored Procedures are checked and ready to go!
